### ISSUE TITLE
Bug: Possible NULL pointer dereference in `cvector_grow`

### ISSUE THREAD

**Issue by jsoltan226** [eteran/c-vector#69]
When `cvector_grow` gets the size of `vec`, it dereferences `vec` before checking if it's NULL

**Comment by eteran** [comment]
Are you referring to this line?

```
const size_t cv_sz__ = (count) * sizeof(*(vec)) + sizeof(cvector_metadata_t);
```

If so, then this is not a `NULL` pointer dereference. `sizeof` is an "unevaluated context", because it happens at compile time. This means that while syntactically, this may look like a dereference of a runtime value, it is not. Instead it is getting the size of the type of the thing that **would be** returned by `*(vec)` if it were evaluated at runtime.

This is actually a common idiom in C for getting the size of an array element.

Hopefully this clears things up. If you are not talking about that line, then please feel free to re-open and clarify.
