### ISSUE TITLE
use in C++

### ISSUE THREAD

**Issue by merlinarer** [eteran/c-vector#70]
Hello, I want use it in C++, because vector is not avaliable. But I met this error:
```
cvector_vector_type(int) v = NULL;
/* add some elements to the back */
cvector_push_back(v, 10);

error:
a value of type "void *" cannot be assigned to an entity of type "int *"C/C++(513)
```

**Comment by nakidai** [comment]
This happens because C++ is more strongly typed and doesn't like such things as changing type behind pointers. You can pass `-fpermissive` to your compiler to suppress the error.

**Comment by eteran** [comment]
What do you mean vector isn't available in C++. Is this an artificial limitation for a class project or something?

In general, if you're using c++, you really should use `std::vector` if you can.

**Comment by eteran** [comment]
Closing because this is a C library, not a C++ library. While it certainly can be altered to work on C++, I'll leave that as an exercise for the reader given that in typical C++ code this library is unnecessary.

**Comment by zkrx** [comment]
I just want to say that sometimes you have C projects that have to use C++ libraries (with things like `extern "C"`). Having cvector arrays in use in some C headers that are then referenced by some C++ code will break the project.

**Comment by eteran** [comment]
Sure, that's a fair enough point. I can look into this a bit.

**Comment by eteran** [comment]
@merlinarer @zkrx So I've looked into this and... it's something that would actually be pretty challenging to do portably.

The main issue is `void *` to T*` conversions. Deep in the code there are things like this:

```
(vec) = cvector_base_to_vec(cv_grow_p2__);
```

Where it is updating the data which `vec` points to, and `cvector_base_to_vec` resolves to a `void *` because we don't know/care what the type of the data is at that point in the code. C++ would want me to add a cast there, but... I don't know the type to cast it to! C23 does have a `typeof` operator, but I'm not sure that this library wants to abandon pre-C23 support.

I'll think on it some more, but can't promise that I'll have a suitable fix in the near term.

**Comment by zkrx** [comment]
Yes I think that C++ requiring correct casting of void * pointers is very annoying for C/C++ compatibility. What I did is I isolated c-vector usage to a C-only module and I provide C wrappers that I call from the C++ side. Something that shouldn't be necessary IMO but what can you do.
